day16/day16/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import depart, user, pretty, admin, account, staff

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    # 正则表达式，传参的时候必须将int传送
    path('depart/<int:nid>/edit/', depart.depart_edit),

    path('depart/test/', depart.depart_test),

    # 用户表

    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 手机号靓号管理

    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),

    # 管理员操作

    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录页面
    path('', account.login),
    path('login/', account.login),
    path('logout/', account.logout),
    path('register/', account.register),

    # 员工登录页面

    path('staff/list/', staff.staff_list),
    path('staff_user/list/', staff.staff_user_list),
    path('staff_depart/list/', staff.staff_depart_list),
    path('staff_pretty/add/', staff.staff_pretty_add),
    path('staff_pretty/<int:nid>/edit/', staff.staff_pretty_edit),
    path('staff_pretty/<int:nid>/delete/', staff.staff_pretty_delete),

]

day16/app01/models.py
from django.db import models

# Create your models here.



class Permissions(models.Model):
    permission_level = models.CharField(verbose_name='权限', max_length=32)
    def __str__(self):
        return self.permission_level


class Admin(models.Model):
    """管理员"""
    username = models.CharField(max_length=32, verbose_name='用户名')
    password = models.CharField(max_length=64, verbose_name='密码')
    Admin_level = models.ForeignKey(verbose_name='管理员权限', to='Permissions', to_field='id', on_delete=models.CASCADE,default=2)


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='标题', max_length=32)
    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name='姓名' ,max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    account = models.CharField(verbose_name='账户余额', max_length=10, default=0)
    create_time = models.DateField(verbose_name='入职时间')

    # 级联删除， 如果部门被删除了，在这个部门下的员工一并被删除
    # 对于外键，django会自动加上_id 也就是depart = depart_id
    depart = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', on_delete=models.CASCADE)

    # 创建了一个元组

    # 目的是为了节省存储空间
    # 在django中会自动帮助我们寻找对应元组的映射
    # obj.get_gender_display() 那么django会自动寻找gender_choices对应的映射
    gender_choices = (
        (1, '男'),
        (2, '女')
    )
    gender = models.SmallIntegerField(choices=gender_choices, verbose_name='性别')
    User_level = models.ForeignKey(verbose_name='员工权限', to='Permissions', to_field='id', on_delete=models.CASCADE, default=3)


class PrettyNum(models.Model):
    """手机号管理"""
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.IntegerField(verbose_name='价格', default=0)

    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )

    level = models.SmallIntegerField(verbose_name='级别', choices=level_choices, default=1)

    status_choices = (
        (1, "已占用"),
        (2, "未使用")
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=2)

day16/app01/views.py
from django.core.exceptions import ValidationError
from django.forms import BaseModelForm
from django.shortcuts import render


from app01.utils.form import UserModelForm, PrettyModelNumForm, PrettyEditModelNumForm


# Create your views here.

from app01 import models
def depart_list(request):

    queryset = models.Department.objects.all()

    return render(request, 'depart_list.html', {'queryset': queryset})


from  django.shortcuts import redirect

def depart_add(request):
    """添加部门"""
    if request.method == 'GET':
        return render(request, 'depart_add.html')

    # title 是否会为空
    title = request.POST.get('title')
    # 保存到数据库
    models.Department.objects.create(title=title)

    return redirect('/depart/list/')


def depart_delete(request):
    """删除部门"""
    nid = request.GET.get('nid')

    models.Department.objects.filter(id=nid).delete()

    return redirect('/depart/list/')


def depart_edit(request, nid):
    """修改部门"""
    if request.method == 'GET':
        # 根据nid去获取对象
        row_object = models.Department.objects.filter(id=nid).first()
        print(row_object.id, row_object.title)
        return render(request, "depart_edit.html", {'row_object': row_object})

    # 从网页获取数据回后台
    title = request.POST.get('title')
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect('/depart/list/')



def depart_test(request):
    return render(request, 'temp_test.html')


def user_list(request):
    """用户管理"""
    # 获取用户列表，将用户列表传到前端
    querySet = models.UserInfo.objects.all()
    # for obj in querySet:
    #     print(obj.name, obj.age, obj.create_time.strftime('%Y-%m-%d'), obj.get_gender_display())


        # 如果想知道该员工是哪个部门，又该如何获取
        # print(obj.depart_id)
        # xx = models.Department.objects.filter(id=obj.depart_id).first()
        # print(xx.title)


        # 上述的操作可以实现，但是django已经帮我们封装好了怎么寻找外键，不然我们定义外键的时候有什么用呢
        # obj.depart 获取数据库中存储的id值，由于已经定义了外键
        # 然后根据id值去寻找department表，再返回一个department对象
        # print(obj.depart.title)


    return render(request, 'user_list.html', {'querySet': querySet})



def user_add(request):
    """添加用户"""

    if request.method == 'GET':
        # gender_choices 是一个元组，然后前端可以通过变量gender_choices获取这个元组
        # 同理depart_list 获取了一众部门的对象，然后传到前端去
        contex = {
            'gender_choice': models.UserInfo.gender_choices,
            'depart_list': models.Department.objects.all()
        }
        return render(request, 'user_add.html', contex)

    # 下列的写法有问题，用户提交的数据没有校验
    # 如果出现错误，应该有错误提示
    # 页面的每个字段都需要写一遍
    name = request.POST.get('user')
    pwd = request.POST.get('pwd')
    age = request.POST.get('age')
    account = request.POST.get('ac')
    ctime = request.POST.get('ctime')
    gender_id = request.POST.get('gd')
    depart_id = request.POST.get('dp')

    # 获取到数据后就可以添加数据了
    # 难道添加外键要加上_id? 不是很理解django这操作，在数据库中
    # django确实是帮我加了_id, 但是我现在添加到噢·····我好像直到了
    # django的orm组件作为一个翻译官，它只负责翻译一些语言，但是具体添加的数据库字段还需要用户自己指定
    # 在指定完后再翻译，然后添加到数据库中，而在通过django创建数据库外键的时候，创建的是depart_id
    # 所以在指定添加的时候，也应该是depart_id
    models.UserInfo.objects.create(name=name, password=pwd, gender=gender_id,
                                   age=age,depart_id=depart_id,create_time=ctime,account=account)

    return redirect('/user/list/')



from django import forms

from app01.utils.bootstrap import BootStrapModelForm




# class UserModelForm(forms.ModelForm):
#     class Meta:
#         model = models.UserInfo
#         fields = ['name', 'password', 'age', 'account', 'create_time', 'gender', 'depart']
#         # 修改models的样式
#         # widgets = {
#         #     "name": forms.TextInput(attrs={'class': 'form-control'}),
#         #     "password": forms.TextInput(attrs={'class': 'form-control'}),
#         #     "age": forms.TextInput(attrs={'class': 'form-control'})
#         # }
#
#     # 重新定义init方法
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#
#         # 循环找到所有的插件，不用向上面的widget那样一个一个手动添加
#         # 对每个循环的字段加一个样式class
#         for name, filed in self.fields.items():
#
#             # placeholder 是默认显示的内容是什么
#             filed.widget.attrs = {'class': 'form-control', 'placeholder':filed.label}
#


def user_model_form_add(request):
    """基于modelform的用户添加"""
    if request.method == 'GET':
        form = UserModelForm()

        return render(request, 'user_model_form_add.html', {"form":form})

    # post 提交 要对数据进行校验
    # 这个data的作用是什么？
    # 对这个form的使用不是很理解，无论是post传过来的还是在校验出错的时候，
    # 直接返回一个form就能重新将错误信息渲染出来是为什么
    form = UserModelForm(data=request.POST)

    if form.is_valid():
        # print(form.cleaned_data)
        # form知道是哪个表，所以会自动翻译，然后在表上添加数据
        form.save()
        return redirect('/user/list/')
    else:
        # 校验失败，在页面上显示错误信息
        print(form.errors)

    return render(request, 'user_model_form_add.html', {"form":form})


def user_edit(request, nid):
    """编辑用户"""

    # 知道了nid，那么就可以从数据库中获取对象出来
    row_object = models.UserInfo.objects.filter(id=nid).first()
    # 这个instance的使用也不是很理解
    form = UserModelForm(instance=row_object)
    if request.method == 'GET':
        return render(request, 'user_edit.html',{'form':form})

    # 加上instance后就代表不是添加数据，而是更新数据到那一行
    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # form.save()是添加数据的，而不是更新数据的
        # 默认保存用户输入的所有数据，如果想保存不是用户输入的数据
        # 可以form.instance = 值
        form.save()
        return redirect('/user/list/')
    return render(request, 'user_edit.html', {"form":form})


def user_delete(request, nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list/')


def pretty_list(request):
    """靓号列表"""

    # 相当于select * from 表 by order desc;
    querySet = models.PrettyNum.objects.all().order_by('-level')

    return render(request, 'pretty_list.html', {'querySet':querySet})


from django import forms



from django.core.validators import RegexValidator





# class PrettyModelNumForm(forms.ModelForm):
#     mobile = forms.CharField(
#         label='手机号',
#         validators=[RegexValidator(r'^1[3-9]\d{9}$', '手机号格式错误')]
#     )
#
#     class Meta:
#         model = models.PrettyNum
#         # 如果是下面的用法，代表fields全选
#         # fileds = "__all__"
#         fields = ['mobile', 'price', 'level', 'status']
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#
#         # 循环找到所有的插件，不用向上面的widget那样一个一个手动添加
#         # 对每个循环的字段加一个样式class
#         for name, filed in self.fields.items():
#             # placeholder 是默认显示的内容是什么
#             filed.widget.attrs = {'class': 'form-control', 'placeholder':filed.label}
#
#
#     # 下面这种方法也能检查输入格式是否是对的
#     # clean是django检查的默认前缀
#     def clean_mobile(self):
#         txt_mobile = self.cleaned_data['mobile']
#         exists = models.PrettyNum.objects.filter(mobile=txt_mobile).exists()
#         if exists:
#             # 刚才写成return了，导致直接返回手机号了，应该要抛出错误才行
#             raise ValidationError('手机号已存在')
#
#     #     if len(txt_mobile) != 11:
#     #         return ValidationError('格式错误')
#         return txt_mobile

def pretty_add(request):
    """靓号增加"""
    if request.method == "GET":
        form = PrettyModelNumForm()
        return render(request, 'pretty_add.html', {"form":form})

    form = PrettyModelNumForm(data=request.POST)

    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')

    return render(request, 'pretty_add.html', {"form":form})



# class PrettyEditModelNumForm(forms.ModelForm):
#     mobile = forms.CharField(
#         disabled=False, label='手机号'
#     )
#
#     class Meta:
#         model = models.PrettyNum
#         fields = ['mobile', 'price', 'level', 'status']
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for name, filed in self.fields.items():
#             filed.widget.attrs = {'class': 'form-control', 'placeholder': filed.label}
#     # 对于编辑的手机号，应该排除自己外的手机号不能重复
#
#     def clean_mobile(self):
#
#         # 拿到当前编辑的那一行手机号的id是多少
#         #  通过instance.pk拿到
#         txt_mobile = self.cleaned_data['mobile']
#         exists = models.PrettyNum.objects.exclude(id=self.instance.pk).filter(mobile=txt_mobile).exists()
#         if exists:
#             raise ValidationError('手机号已经存在')
#         return txt_mobile


def pretty_edit(request,nid):
    """靓号编辑"""

    row_object = models.PrettyNum.objects.filter(id=nid).first()

    if request.method == 'GET':
        form = PrettyEditModelNumForm(instance=row_object)
        return render(request, 'pretty_edit.html', {"form":form})

    form = PrettyEditModelNumForm(data=request.POST,instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')

    return render(request, 'pretty_edit.html', {"form":form})


def pretty_delete(request,nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/pretty/list/')

day16/app01/views/account.py
from django.contrib.auth.forms import UserChangeForm
from django.forms import BaseModelForm
from django.http import HttpResponseRedirect, HttpResponse

from app01.utils.encrypt import md5
from app01.utils.form import UserModelForm, PrettyModelNumForm, PrettyEditModelNumForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django import forms
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm



class LoginForm(forms.Form):
    username = forms.CharField(
        label='用户名',
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required=True
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={"class":"form-control"}),
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

def login(request):
    """登录"""
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {"form":form})

    form = LoginForm(data=request.POST)

    if form.is_valid():

        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()

        if admin_object is not None:
            request.session["info"] = {'id': admin_object.id, 'username': admin_object.username}
            return redirect('/admin/list/')

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user_object = models.UserInfo.objects.filter(name=username,password=password).first()
        if user_object is not None:
            request.session["info"] = {'id': user_object.id, 'username': user_object.name}
            return redirect('/staff/list/')

        # if not admin_object:
        #     # 放在password是为了错误信息显示在密码下方
        form.add_error("password", "用户名或密码错误")
        #     return render(request, 'login.html', {"form": form})

        # request.session["info"] = {'id': admin_object.id, 'username': admin_object.username}
        #
        # return redirect('/admin/list/')
        #
        # user_object = models.UserInfo.objects.filter(**form.cleaned_data).first()
        #
        # if not user_object:
        #     md5(cleaned_data['password'])
        #     return render(request, 'login.html', {"form": form})
        # return redirect('/admin/list/')

    return render(request, 'login.html', {"form":form})



class UserExModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput
    )

    class Meta:
        model = models.UserInfo
        fields = ['name', 'password', 'confirm_password', 'age', 'create_time', 'depart', 'gender']
        widgets = {
            "password": forms.PasswordInput
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        # print("whereis mde"+md5(pwd))
        return md5(pwd)

    # 在前端增加一个校验格式的函数
    def clean_confirm_password(self):
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("密码不一致")

        return confirm


def register(request):

    if request.method == 'GET':
        form = UserExModelForm()
        return render(request, 'register.html', {"form":form})

    form = UserExModelForm(data=request.POST)

    if form.is_valid():
        form.save()
        return redirect('/login/')
    else:
        # 校验失败，在页面上显示错误信息
        print(form.errors)

    return render(request, 'register.html', {"form":form})
    # return redirect('/login/')
    # return render(request, 'register.html')



def logout(request):
    """注销"""

    request.session.clear()
    return redirect('/login/')

day16/app01/templates/admin_list.html
{% extends 'layout.html' %}


{% block content %}

    <div>
        <div class="container">
            <div style="margin-bottom: 10px">
                <a class="btn btn-primary" href="/admin/add/" target="_blank">新建管理员</a>
            </div>

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    管理员列表
                </div>
                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>用户名</th>
                        <th>密码</th>
                        <th>重置密码</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in querySet %}
                        <tr>
                            <th scope="row">{{ obj.id }}</th>
                            <td>{{ obj.username }}</td>
                            <td>**********</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/reset/">重置密码</a>
                            </td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">编辑</a>
                                <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
{% endblock %}

day16/app01/templates/change.html
{% extends 'layout.html' %}


{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ title }}</h3>
                </div>

                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {#                                <input type="text" class="form-control" placeholder="姓名" name="user"/>#}
                                {{ field }}
                                {#                                如果有错误信息，增加提示#}
                                <span style="color:red">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>

                </div>

            </div>
        </div>
    </div>

{% endblock %}










{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{##}
{#        {% for fields in form %}#}
{#            {{ fields.label }}:{{ fields }}#}
{#        {% endfor %}#}

{#        {{ form.name.label }}:{{ form.name }}#}
{#        {{ form.password.label }}:{{ form.password }}#}
{#        {{ form.age.label}}:{{ form.age }}#}
{#    </form>#}
{#</body>#}
{#</html>#}

day16/app01/templates/depart_add.html
{#{% load static %}#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">#}
{#</head>#}
{#<body>#}
{#<nav class="navbar navbar-default">#}
{#    <div class="container-fluid">#}
{#        <!-- Brand and toggle get grouped for better mobile display -->#}
{#        <div class="navbar-header">#}
{#            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"#}
{#                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">#}
{#                <span class="sr-only">Toggle navigation</span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
{#            <a class="navbar-brand" href="#">联通用户管理菜单</a>#}
{#        </div>#}
{##}
{#        <!-- Collect the nav links, forms, and other content for toggling -->#}
{#        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{#            <ul class="nav navbar-nav">#}
{#                <li class="active"><a href="/depart/list/">部门管理 <span class="sr-only">(current)</span></a></li>#}
{#                <li><a href="#">Link</a></li>#}
{#                <li class="dropdown">#}
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">Dropdown <span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="#">Action</a></li>#}
{#                        <li><a href="#">Another action</a></li>#}
{#                        <li><a href="#">Something else here</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">Separated link</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">One more separated link</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#            </ul>#}
{#            <form class="navbar-form navbar-left">#}
{#                <div class="form-group">#}
{#                    <input type="text" class="form-control" placeholder="Search">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default">Submit</button>#}
{#            </form>#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a href="#">登录</a></li>#}
{#                <li class="dropdown">#}
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">谷雨 <span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="#">个人资料</a></li>#}
{#                        <li><a href="#">我的信息</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">注销</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#            </ul>#}
{#        </div><!-- /.navbar-collapse -->#}
{#    </div><!-- /.container-fluid -->#}
{#</nav>#}

{% extends 'layout.html' %}
{% block content %}

<div>
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建部门</h3>
            </div>


            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>标题</label>
                        <input type="text" class="form-control"  placeholder="标题" name="title"/>
                    </div>

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>

            </div>

        </div>
    </div>
</div>


{% endblock %}


{#<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>#}
{#<script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>#}
{##}
{##}
{#</body>#}
{#</html>#}

day16/app01/templates/pretty_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">手机号编辑</h3>
                </div>

                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {#                                <input type="text" class="form-control" placeholder="姓名" name="user"/>#}
                                {{ field }}
                                {#                                如果有错误信息，增加提示#}
                                <span style="color:red">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>

                </div>

            </div>
        </div>
    </div>

{% endblock %}

day16/app01/templates/staff_list.html
{% extends 'staff_info.html' %}


{% block content %}
     <div>
        <div class="container">
            <div style="margin-bottom: 10px">
                <a class="btn btn-primary" href="/staff_pretty/add/" target="_blank">新建手机号</a>
            </div>

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    手机号列表
                </div>
                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>号码</th>
                        <th>价格</th>
                        <th>级别</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in querySet %}
                        <tr>
                            <th scope="row">{{ obj.id }}</th>
                            <td>{{ obj.mobile}}</td>
                            <td>{{ obj.price }}</td>
                            <td>{{ obj.get_level_display }}</td>
                            <td>{{ obj.get_status_display }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="/staff_pretty/{{ obj.id }}/edit/">编辑</a>
                                <a class="btn btn-danger btn-xs" href="/staff_pretty/{{ obj.id }}/delete/">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

{% endblock %}